import { Header } from "@/components/header";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./styles/globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased dark flex flex-col flex-start items-center min-h-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
